# v2
services:
  client:
    container_name: pp-client
    build:
      context: .
      dockerfile: packages/client/prod.Dockerfile
    pull_policy: build
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - pp-network

  ingress:
    container_name: pp-ingress
    build:
      context: ./packages/ingress
      dockerfile: prod.Dockerfile
    pull_policy: build
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - pp-network

networks:
  pp-network:
